// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubnhcfntngcqyzmbfvxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVibmhjZm50bmdjcXl6bWJmdnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzAwOTIsImV4cCI6MjA2ODMwNjA5Mn0.pEizRsW3Z1U-y9FLoZLUNQ-_4mHZkStQS-8gPTFuPdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});